# Generated by Django 2.2.7 on 2020-01-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20200107_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dept',
            new_name='Stream',
        ),
    ]
