# Generated by Django 2.2.7 on 2020-01-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auto_20200107_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Junior',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
