# Generated by Django 2.2.7 on 2020-01-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_highschool_intermediate_junior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=30)),
                ('motherName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('mono', models.IntegerField()),
                ('qualification', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('dob', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
