# Generated by Django 2.2.7 on 2020-01-12 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_car_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('classId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='college.Class')),
                ('rollno', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
