# Generated by Django 2.2.7 on 2020-01-13 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20200113_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHighSchool',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Class')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceIntermediate',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Class')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceJunior',
            fields=[
                ('rollno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Class')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='classId',
        ),
        migrations.DeleteModel(
            name='HighSchool',
        ),
        migrations.DeleteModel(
            name='Intermediate',
        ),
        migrations.DeleteModel(
            name='Junior',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
