# Generated by Django 2.2.7 on 2020-01-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20200113_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=7)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Class')),
                ('rollno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendanceintermediate',
            name='class_id',
        ),
        migrations.RemoveField(
            model_name='attendancejunior',
            name='class_id',
        ),
        migrations.DeleteModel(
            name='AttendanceHighSchool',
        ),
        migrations.DeleteModel(
            name='AttendanceIntermediate',
        ),
        migrations.DeleteModel(
            name='AttendanceJunior',
        ),
    ]
