# Generated by Django 2.2.7 on 2020-03-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='amount',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='class_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='college.Class'),
            preserve_default=False,
        ),
    ]
