# Generated by Django 2.2.7 on 2020-03-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_auto_20200311_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='bankTxnId',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='txnDate',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fee',
            name='txnId',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fee',
            name='orderId',
            field=models.CharField(max_length=40),
        ),
    ]
