# Generated by Django 2.2.7 on 2020-03-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_auto_20200311_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='detail',
        ),
    ]
