# Generated by Django 2.2.7 on 2019-12-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20191206_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ManageQuestion')),
                ('testId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.Test')),
            ],
        ),
    ]
