# Generated by Django 2.2.7 on 2019-12-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_test_testquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='password',
            field=models.CharField(default=200, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='timer',
            field=models.CharField(default='200ghhjj', max_length=4),
            preserve_default=False,
        ),
    ]
