# Generated by Django 2.2.7 on 2020-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
            ],
        ),
    ]
