# Generated by Django 2.2.7 on 2020-01-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_quizresult1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResult1',
            new_name='QuizResult2',
        ),
    ]
