# Generated by Django 2.2.7 on 2020-01-10 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_auto_20200110_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizResult2',
            new_name='QuizResult3',
        ),
    ]
