# Generated by Django 2.2.7 on 2020-01-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20200110_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='marks',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresult',
            name='testId',
            field=models.CharField(default=98, max_length=30),
            preserve_default=False,
        ),
    ]
