# Generated by Django 2.2.7 on 2020-03-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20200111_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
